apiVersion: v1
kind: Service
metadata:
  name: dojo-service
spec:
  selector:
    app: dojo-jump
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30010